# Generated by Django 3.2 on 2022-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('balance', models.FloatField(default=0.0, verbose_name='Balance')),
                ('currency', models.CharField(choices=[('pln', 'PLN'), ('usd', 'USD'), ('eur', 'EUR')], default='pln', max_length=3, verbose_name='Currency')),
                ('max_debit', models.FloatField(default=100.0, verbose_name='Max debit')),
                ('ban', models.CharField(max_length=32, unique=True, verbose_name='Bank account number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_date', models.DateTimeField(auto_now=True)),
                ('from_ban', models.CharField(max_length=32, verbose_name='From bank account number')),
                ('to_ban', models.CharField(max_length=32, verbose_name='To bank account number')),
                ('outer_transfer', models.BooleanField(verbose_name='Outer transfer')),
                ('currency', models.CharField(choices=[('pln', 'PLN'), ('usd', 'USD'), ('eur', 'EUR')], default='pln', max_length=3, verbose_name='Currency')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name and address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
