# Generated by Django 3.2 on 2022-03-09 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_create_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='account.account', verbose_name='From account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='account.account', verbose_name='To account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_write_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='create_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_create_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_write_uid', to=settings.AUTH_USER_MODEL),
        ),
    ]
